### ISSUE TITLE
Passes/Excludes no longer works

### ISSUE THREAD

**Issue by henry-cotton** [kokororin/vscode-phpfmt#105]
After the update to 1.15, the passes/exclude fields declare that all the options are invalid.
I've had the demo for using tabs rather than spaces from the start, but it now no longer works.

My settings.json:
`"phpfmt.enable_auto_align": true,
    "phpfmt.indent_with_space": 4,
    "phpfmt.passes": [
        "PSR2KeywordsLowerCase",
        "PSR2LnAfterNamespace",
        "PSR2CurlyOpenNextLine",
        "PSR2ModifierVisibilityStaticOrder",
        "PSR2SingleEmptyLineAndStripClosingTag",
        "ReindentSwitchBlocks"
    ],
    "phpfmt.exclude": ["ReindentComments", "StripNewlineWithinClassBody"],
    "phpfmt.psr1": true,
    "phpfmt.psr2": false,
    "[php]": {
        "editor.defaultFormatter": "kokororin.vscode-phpfmt"
    },
    "editor.formatOnSave": true`

However, saving now gives the error message:

phpfmt: passes or exclude invalid: PSR2KeywordsLowerCase, PSR2LnAfterNamespace, PSR2CurlyOpenNextLine, PSR2ModifierVisibilityStaticOrder, PSR2SingleEmptyLineAndStripClosingTag, ReindentComments

**Comment by kokororin** [comment]
We have upgrade to new fmt.phar, which not includes some of the old passes.

**Comment by kokororin** [comment]
fixed in 1.1.6
