### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by jcrasgado** [kokororin/vscode-phpfmt#106]
In the last update, I got this error.

phpfmt: Error getting php version

I haven't changed anything, just update and I don't know what to configure.

phpfmt v1.1.5

VSCode
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.12-200.fc37.x86_64
Sandboxed: No

**Comment by jcrasgado** [comment]
![image](https://user-images.githubusercontent.com/2680188/235767747-0c6b8971-1f9f-4857-b78d-4f2e2a91107d.png)

The console show this error

**Comment by kokororin** [comment]
maybe the php verison of yours is not correct, we will release a new version to support php 5.6

**Comment by kokororin** [comment]
fixed in 1.1.6
