### ISSUE TITLE
PHP is invalid

### ISSUE THREAD

**Issue by jcrasgado** [kokororin/vscode-phpfmt#107]
Thanks for the quick response to the above problem.

I found a new problem, I hope I can explain it well..

First you must enable and configure **xdebug.mode = debug** and  **xdebug .start_with_request = yes**

When this setting is enabled and they do not have a debugging client active, the following error is thrown and the plugin fails

![image](https://user-images.githubusercontent.com/2680188/235975263-05c13534-af74-423f-a5cd-9ebe6078f1ab.png)

![image](https://user-images.githubusercontent.com/2680188/235975234-c11d7d26-35ef-46dc-a9ff-8bc2be087408.png)

If the debugging client is active, this error goes away

![image](https://user-images.githubusercontent.com/2680188/235976022-1850f29c-4939-435a-8399-83cc48e229a6.png)

![image](https://user-images.githubusercontent.com/2680188/235976054-bc77dfd7-993d-45da-9c49-f4b9929a634c.png)

I found a solution setting **xdebug.log_level = 0**

I don't know if this works for everyone because by default xdebug keeps the log_level to 7 aand probably many use this value

![image](https://user-images.githubusercontent.com/2680188/235980060-2f1de755-ebd3-460d-b654-c76d582d105f.png)

Thank you for your time, and I hope the information is helpful.

**Comment by kokororin** [comment]
Hi @jcrasgado 

Can you confirm if version 1.1.7 fixes this issue?
