### ISSUE TITLE
Constant arrays on classes causes all keywords before function to be removed

### ISSUE THREAD

**Issue by Christian-Rinne** [kokororin/vscode-phpfmt#112]
Duplicate of #42 

The bug still persists (v 1.1.9)

**Comment by Christian-Rinne** [comment]
I believe it only happens to me when methods are named 'print'.

**Comment by driade** [comment]
Should be fixed in https://github.com/driade/phpfmt8/issues/37

**Comment by Christian-Rinne** [comment]
fixed see #42
