### ISSUE TITLE
Can or does this support PSR-12

### ISSUE THREAD

**Issue by dranzd** [kokororin/vscode-phpfmt#113]
I have a class that has this method in this format:

`final public function log(AggregateEvent $aggregateEvent): ?int`

but when I ran the formatter it converts it to

`final public function log(AggregateEvent $aggregateEvent):  ? int`

Can this be fixed?  If not, how to resolve it?

Tech info:
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 4.15.0-20-generic

Thanks!

**Comment by driade** [comment]
Hello @dranzd , good morning. It seems you may be running an old version of the parser, as this error was fixed on

https://github.com/driade/phpfmt8/commit/3e0cd07fffc16008e50a02840396286158f89c6e

may you please run the command "phpfmt: Upgrade fmt.phar ot fmt.stub.php"?

In case this doesn't work, please check that "phpfmt.use_old_phpfmt" is false in your configuration so you can use the new parser. I suppose you already do.

If nothing works I'd recommend reinstalling the plugin to get the most updated version.

Thanks.

**Comment by dranzd** [comment]
Hello @driade, 

Thank you for that.  You are correct that I might be running an older version as I switched temporarily to a different parser and when I turn it back on the issue no longer occurs.

Thanks again for your help!
