### ISSUE TITLE
Keywords get replaced incorectly

### ISSUE THREAD

**Issue by hudecv** [kokororin/vscode-phpfmt#118]
Dear author,

keywords are incorrectly identified in places which do not represent them. Example:

Before:

`ICollection::OR`

After:

`ICollection:: or` `<- mind the space`

The lowercase replacement can be mitigated by disabling the pass "PSR2KeywordsLowerCase", byt the extra whitespace is still being added.

Could you fix that?

**Comment by driade** [comment]
Hi @hudecv, fixed.

May you please run the command "phpfmt: Upgrade fmt.phar ot fmt.stub.php" and check?

Thanks.

**Comment by hudecv** [comment]
Hey @driade,

works like a charm. Great stuff.

Thanks for such a quick reply
