### ISSUE TITLE
Possible incorrect conversion of line with method name having reserved word "include"

### ISSUE THREAD

**Issue by dranzd** [kokororin/vscode-phpfmt#119]
I have a class that has this method in this format:

`final public function include(Documents $documents): Documents`

but when I ran the formatter it converts it to

`function include Documents $documents:Documents {`

Is this expected?

Tech info:

> Extension ID: kokororin.vscode-phpfmt (v.1.1.12)
> Version: 1.81.1
> Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
> Date: 2023-08-09T22:18:39.991Z
> Electron: 22.3.18
> ElectronBuildId: 22689846
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Linux x64 4.15.0-20-generic

**Comment by driade** [comment]
Hello, good morning. Bug confirmed and fixed.

May you please run the command "phpfmt: Upgrade fmt.phar ot fmt.stub.php" and check?

Thanks.

**Comment by dranzd** [comment]
Hey @driade ,

That was quick, thank you!  I can confirm this is now fixed.

Thanks again!

**Comment by dranzd** [comment]
Sorry I had to reopen again.

I just noticed now that the opening curly brace is not going on another line, so from:

```
    final public function include(Documents $documents): Documents {
```

I believe it should be 

```
    final public function include(Documents $documents): Documents 
    {
```

Thanks!

**Comment by driade** [comment]
Thanks, fixed, may you please cofirm?

**Comment by dranzd** [comment]
Perfect!  Thank you very much specially for fixing that quickly!
