### ISSUE TITLE
Issue with StripSpaceWithinControlStructures Pass in PHP Formatting

### ISSUE THREAD

**Issue by ferhado** [kokororin/vscode-phpfmt#127]
---

Hi,

I've encountered an issue with the `StripSpaceWithinControlStructures` pass in PHP formatting. The pass seems to incorrectly format the enum structure, especially with the method signature.

### Before Formatting:
```php
namespace App\Enums;

enum InvoiceStatus: string {
  case DRAFT = 'draft';
  case UNPAID = 'unpaid';
  case PAID = 'paid';
  case PARTIAL = 'partial';

  public static function isValid(string $status): bool {
    return in_array($status, self::cases(), true);

  }
}
```

### After Formatting:
```php
namespace App\Enums;

enum InvoiceStatus: string {
  case DRAFT = 'draft';
  case UNPAID = 'unpaid';
  case PAID = 'paid';
  case PARTIAL = 'partial';

  public static function isValid(string $status):  
  bool {
    return in_array($status, self::cases(), true);
  }
}
```

As you can see, after formatting, the return type `bool` of the `isValid` method is incorrectly moved to the next line. This change doesn't align with standard PHP formatting practices and could potentially lead to readability issues.

Could you please look into this issue?

Thanks,
ferhado

**Comment by driade** [comment]
Thank you, this should be fixed, may you confirm?

**Comment by ferhado** [comment]
Confirmed, thank you for fastest support
