### ISSUE TITLE
The options does not work

### ISSUE THREAD

**Issue by juangber** [kokororin/vscode-phpfmt#13]
I am on macOS High Sierra and the plugin is working, but it does not interpret any options given, I turned on the debug and I see that the command is actually calling the args correctly but nothing happen on my code. I try running the command in the terminal with the real path and work correctly.

This screenshot is before running the format
<img width="1440" alt="screen shot 2018-02-14 at 15 32 59" src="https://user-images.githubusercontent.com/6562032/36226720-a6fec192-119c-11e8-8805-bb3bf896a9fc.png">

And this after the format
<img width="1440" alt="screen shot 2018-02-14 at 15 33 06" src="https://user-images.githubusercontent.com/6562032/36226748-b8562f02-119c-11e8-8ec5-ab2c34edb781.png">

If you see the "after" and command launched the code should look totally different

**Comment by kokororin** [comment]
PSR2 with `indent_with_space=2` may not work, it must be 4 with PSR2.

**Comment by juangber** [comment]
But if I run the command on the terminal it works. Also the alignment of EQUALS and the ShortArray transform.

**Comment by kokororin** [comment]
I use this extension on macOS 10.12.6 and it works. So i don't know how to deal with this.
