### ISSUE TITLE
Error on formatting anonymous class

### ISSUE THREAD

**Issue by d-enk** [kokororin/vscode-phpfmt#134]
```php
<?php

$obj = (new class
{
    private $field;

    public function method(): void
    {
    }
});
```

Different behavior when there is a `$field`, `class ()`, `public`

**Comment by driade** [comment]
Hi, I'm working on it. This bug is produced by a recent update to prevent other bug.

**Comment by driade** [comment]
Hi @d-enk this should be fixed. May you please confirm? Thanks.

**Comment by d-enk** [comment]
confirmed) thanks
