### ISSUE TITLE
Throws an error in VS Code

### ISSUE THREAD

**Issue by codepen22** [kokororin/vscode-phpfmt#135]
03:11:36.197 [INFO] Extension Version: 1.1.34
03:11:43.195 [INFO] settings reloaded
03:11:43.222 [INFO] settings reloaded
03:11:43.261 [INFO] settings reloaded
03:12:19.450 [ERROR] getting php version failed
Cannot load Zend OPcache - it was already loaded

03:12:19.452 [ERROR] Format failed
03:12:19.452 [ERROR] phpfmt: "php -v" returns non-zero code
03:13:39.389 [ERROR] getting php version failed
Cannot load Zend OPcache - it was already loaded

03:13:39.391 [ERROR] Format failed
03:13:39.392 [ERROR] phpfmt: "php -v" returns non-zero code
03:17:29.383 [ERROR] getting php version failed
Cannot load Zend OPcache - it was already loaded

03:17:29.386 [ERROR] Format failed
03:17:29.386 [ERROR] phpfmt: "php -v" returns non-zero code

**Comment by codepen22** [comment]
Alsways throws this error, i am not sure what is the problem, had to uninstall

**Comment by kokororin** [comment]
Can you show the output of `php -v`

**Comment by kokororin** [comment]
fixed.
