### ISSUE TITLE
space after type casting

### ISSUE THREAD

**Issue by cDonut** [kokororin/vscode-phpfmt#138]
Can't find way to remove space after type casting.
formatting `(int)$userId` will be `(int) $userId`
Can I remove this rule somehow?

**Comment by cDonut** [comment]
seems that Cakephp option solved my problem

**Comment by cDonut** [comment]
sadly Cakephp option is bringing another formating changes.
Can I control casting space separately?

**Comment by driade** [comment]
Hi, good afternoon. This is not possible as the rule that adds these spaces is in charge of controlling spaces in many other places in the code.

You can disable it and try adding "ResizeSpaces" to your "Exclude" rules.

Cheers,

**Comment by cDonut** [comment]
Thanks, I'll try some combinations with exclude rules
