### ISSUE TITLE
"phpfmt.exclude": ["AllmanStyleBraces"] Not working

### ISSUE THREAD

**Issue by Jursdotme** [kokororin/vscode-phpfmt#14]
```
    "phpfmt.passes": [
        "AlignGroupDoubleArrow"
    ],
    "phpfmt.debug_mode": true,
    "phpfmt.exclude": [
        "AllmanStyleBraces"
    ]
```
Shouldnt this disable the Allman Style linebraks before brace opening? I want the regular K&R style.

**Comment by adoo** [comment]
Why is this closed? It's not working :)

**Comment by Harryki** [comment]
yeah i want K&R style as well

**Comment by Harryki** [comment]
@adoo, @Jursdotme any of you find the solution? i've opened issue once more on #21 but that didn't work on mine
