### ISSUE TITLE
SpaceAroundParentheses creates adds two space chars for nested parentheses

### ISSUE THREAD

**Issue by PrinceOfAbyss** [kokororin/vscode-phpfmt#143]
My settings JSON in regard to phpfmt formatting has the following array:

    "phpfmt.passes": [
        "AlignDoubleArrow",
        "AutoPreincrement",
        "DoubleToSingleQuote",
        //"LongArray",
        "ShortArray",
        "SpaceAroundParentheses",
        "SpaceAfterExclamationMark",
    ],

My problem is that `SpaceAroundParentheses`, as its name implies, literally adds one space char *after* the first paren, and then adds one more *before* the second parent, thus resulting in two, consequent space chars between the two opening parens. Of course I may be wrong, but this seems like the most probable scenario to me.

So, if that's the case, I think that  `SpaceAroundParentheses` should function more like  `SpaceAroundParenthesesInternally`, in order to add a space char after (inside) the first opening paren, then add one more after (again inside) the second opening paren, and then add one before each of the closing parens (still inside them).

So to give you and example of the problem, this:

            if ( ( $min <= $cart_item['data']->get_weight() ) && ( $cart_item['data']->get_weight() < $max ) ) {

after formatting becomes like this:

            if (  ( $min <= $cart_item['data']->get_weight() ) && ( $cart_item['data']->get_weight() < $max ) ) {

**Comment by driade** [comment]
Hmm, now that I see what you mean I think that it's clear there's a bug in the current rule, where we've two spaces where it surely must be one. Please let me check.

**Comment by PrinceOfAbyss** [comment]
Exactly that @driade! Thank you very much!

**Comment by driade** [comment]
There you've, it should be already fixed.

**Comment by PrinceOfAbyss** [comment]
@driade any ETA on this being released as an update to VS.Code?

**Comment by driade** [comment]
I'm not entirely sure about how the changes are synced to VSCode. From what I understand, it's fast, but I'm uncertain about the specifics.

**Comment by kokororin** [comment]
The automatic update script has some issues; version 1.2.1 has been released now.

**Comment by PrinceOfAbyss** [comment]
Indeed the bug is corrected now! Thanks @kokororin
