### ISSUE TITLE
Use PSR12

### ISSUE THREAD

**Issue by karchung0930** [kokororin/vscode-phpfmt#144]
I cannot find any information on the documentation whether it's possible to use PSR12 instead of PSR2. I saw the setting `phpfmt.psr2` is set to true by default. Or this extension is already using PSR12 but the information is not updated on the documentation yet?

**Comment by driade** [comment]
Hi @karchung0930 good morning.

No, there're no plans to support PSR12 at this moment. It's something I've in my backlog.
