### ISSUE TITLE
How to space around arrows after formatting my code?

### ISSUE THREAD

**Issue by Shams-Raju** [kokororin/vscode-phpfmt#147]
![image](https://github.com/kokororin/vscode-phpfmt/assets/63977867/c984ec04-7a1b-4d0e-89bd-5169035d91f5)

**Comment by driade** [comment]
Hi. Could you please post an example on would you expect the code to be formatted? Thanks.

**Comment by Shams-Raju** [comment]
> Hi. Could you please post an example on would you expect the code to be formatted? Thanks.

Space around arrow like this: 
![image](https://github.com/kokororin/vscode-phpfmt/assets/63977867/858dffa4-4148-4428-8afe-2385fc2a8bcb)

**Comment by driade** [comment]
Si @Shams-Raju There's no current rule in phpfmt to achieve this, nor there's no recommendation in the PSR standards https://www.php-fig.org/psr/ that suggest this behaviour.

Therefore it's not expected that this package should have this rule. It'd be a custom rule, opt in, that we had to develop.

**Comment by driade** [comment]
No. Regards.
