### ISSUE TITLE
phpfmt.wp -  What does "WP style" mean?

### ISSUE THREAD

**Issue by sephentos** [kokororin/vscode-phpfmt#149]
```phpfmt.wp | boolean | activate WP style```

What exactly does the WP parameter stand for? Wordpress styles? What exactly happens when this is active? In the source code, I only see that a --wp parameter is set as arg.

**Comment by driade** [comment]
Hi @sephentos good morning. This option activates the same rules as PSR2 and additionally other (WPResizeSpaces) to match the WP style guide. Please see https://github.com/driade/phpfmt8/issues/33
