### ISSUE TITLE
"ReplaceIsNull" is adding a bug to my code

### ISSUE THREAD

**Issue by adrianahdez** [kokororin/vscode-phpfmt#154]
Hi,

This block normally return `true` as it is:

```
function get_number() {
	return '334';
}

if ( !is_null( $n = get_number() ) ) {
	// do something with $n...
	var_dump(true);
} else {
	var_dump(false);
}
```

And the "ReplaceIsNull" option is changing that `if()` statement to this:

`if ( !null === $n = get_number() ) { ... }`

Which is wrong, because it's returning false and it's adding a bug to the code.

In this case, it should be changed to this, in order to work fine:

` if ( null !== $n = get_number() ) { ...}`

**Comment by driade** [comment]
This one was easy, fixed in the latest version

**Comment by adrianahdez** [comment]
oh, that was fast. 
Many thanks :)
