### ISSUE TITLE
phpfmt.passes -> OnlyOrderUseClauses :: Value is not accepted.

### ISSUE THREAD

**Issue by julesgilson** [kokororin/vscode-phpfmt#156]
### The `OnlyOrderUseClauses` setting is not one of accepted values

Visual Studio Code v1.93.1 Windows Desktop
phpfmt extension v1.2.16

VSC Settings
```
"phpfmt.passes": [
    "OnlyOrderUseClauses",
  ],
```
`OnlyOrderUseClauses`: Value is not accepted.

---

### From Docs:
# Supported Transformations
| Key | Description |
|:----|:--------------|
| ... | ... |
| OnlyOrderUseClauses | Order use block - do not remove unused imports. |
| ... | ... |

**Comment by kokororin** [comment]
Thank you for reporting the issue. It has been fixed in the latest release.

**Comment by julesgilson** [comment]
**Confirmed as fixed in 1.2.17**

Thanks.
