### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by koossaayy** [kokororin/vscode-phpfmt#158]
I am using PHP 8.4.1 and it seems the extension is not supporting it.

**Comment by driade** [comment]
Hi @kokororin I can confirm the bug. The underlying package supports PHP 8.4. 

May it be related to the way versions are compared?

<img width="484" alt="Captura de pantalla 2024-11-29 a las 16 39 01" src="https://github.com/user-attachments/assets/234dcfea-f524-4bf3-83dc-df55f24f1461">

**Comment by wahid-eng** [comment]
I am also facing same issue.
My PHP version: `8.4.1`
phpfmt: `v1.2.22`

**Comment by kokororin** [comment]
I have removed the PHP 8.4 version check in v1.2.23.

**Comment by wahid-eng** [comment]
It works now. Thank you for the fixing!
