### ISSUE TITLE
"phpfmt.exclude": ["AllmanStyleBraces"]

### ISSUE THREAD

**Issue by adoo** [kokororin/vscode-phpfmt#16]
This is not working...

**Comment by kokororin** [comment]
`AllmanStyleBraces ` is not activated in default options. Why do you exclude it?

**Comment by adoo** [comment]
These are my default args:
`php /bin/fmt.phar --psr2 --indent_with_space=4 /var/x/x/x/T/x.php`
I suppose psr2 is enabling AllmanStyleBraces.

**Comment by adoo** [comment]
Also, if I do `"phpfmt.psr2": false`, then the `AllmanStyleBraces ` is not activated :)

**Comment by kokororin** [comment]
PSR2 is not enabling `AllmanStyleBraces`.
And `AllmanStyleBraces` is not enabing by default.
If you want to enable `AllmanStyleBraces`, try using 
```
phpfmt.passes: ["AllmanStyleBraces"]
```
