### ISSUE TITLE
phpfmt: cannot find php bin

### ISSUE THREAD

**Issue by bardware** [kokororin/vscode-phpfmt#19]
Hi,

I don't have PHP directory on my `PATH` when I start `code`. I Add this setting to my user settings: `"phpfmt.php_bin": "C:/Program Files/php/7_2-nts/php.exe"`, yet your plugin keeps complaing `phpfmt: cannot find php bin`.
Why is that? Does the plugin try to evaluate the path to `php.exe` somehow?

Best,
Bernhard

**Comment by kokororin** [comment]
No, it just means the path is calling php error.
path like `Program Files` with spaces may not work well.
You can try `"phpfmt.php_bin": "'C:/Program Files/php/7_2-nts/php.exe'"`.

**Comment by RicardoBer** [comment]
Form Windows:

After al lot of trys, very simple, I can't understand all the blogs about

install phpfmt from F1 command or plugins UI vs tool

Then add to your settings this lines if you intall php in Program Files: 

"phpfmt.php_bin": "C:\\Progra~1\\PHP\\php.exe",
"php.validate.executablePath":  "C:\\Progra~1\\PHP\\php.exe",

Any way, for know path without spaces (generate problems) open cmd and type dir /x
