### ISSUE TITLE
issue of format_on_save

### ISSUE THREAD

**Issue by gaoyuan121** [kokororin/vscode-phpfmt#2]
Hi,
 I followed these steps:
  1.open a PHP file
  2. change something and press "ctrl+s" to save it, then it will be formatted correctly.
  3.However, I noticed that there is an unsaved sign on the resources label
  4. So I press ctrl+s to save it again without any changes
  5. After step 4, the auto format never take any effect.
Could you please help me out? I like the align module very much.
Thanks for your wonderful plugin.

**Comment by kokororin** [comment]
Maybe there is issue in Windows.
Is your operation system Windows? 
I cannot reproduced it in Linux and macOS.

**Comment by adrian1207** [comment]
I had the same problem on Windows (there was no problem on Linux).
I solved it by changing editor.formatOnSaveTimeout setting to higher value. Default value is 750ms which is too short time in bigger files to format before save. For me `"editor.formatOnSaveTimeout": 5000` work on every file.
