### ISSUE TITLE
php_bin path with DOT, don't work

### ISSUE THREAD

**Issue by rafso** [kokororin/vscode-phpfmt#20]
php_bin path with DOT, don't work, 
ex: 
"D:\\xampp7.1\\php\\php.exe" - don't work
"D:\\xampp71\\php\\php.exe" - its ok

**Comment by kokororin** [comment]
I have tried `"phpfmt.php_bin": "D:\\tools\\phpStudy.2\\PHPTutorial\\php\\php-7.1.13-nts\\php.exe"`, it works.
