### ISSUE TITLE
How to change formatting setting to have K&R style? instead of Allmen style?

### ISSUE THREAD

**Issue by Harryki** [kokororin/vscode-phpfmt#21]

**Comment by mleopold** [comment]
Hi,
I was wondering the same thing. While I haven't any documentation poiting to why, this seems to do the trick for me. Create .phpfmt.ini with the following content below and add a special-argument parameter to your User Settings in vscode:
`    "phpfmt.custom_arguments": "--config=~/.phpfmt.ini"
`
.phpfmt.ini
```
indent_with_space=2
cakephp=1
passes=AlignTypehint,AlignEquals,AlignDoubleArrow

```

**Comment by kokororin** [comment]
Or just like this:
```json
{
  "phpfmt.indent_with_space": 2,
  "phpfmt.cakephp": true,
  "phpfmt.passes": ["AlignTypehint", "AlignEquals", "AlignDoubleArrow"]
}
```

**Comment by Harryki** [comment]
this just result in more indentation spaces. 

curly braces after function still goes in next line

**Comment by Harryki** [comment]
@kokororin Excellent! that works!

**Comment by abhagsain** [comment]
@Harryki @kokororin It's not working for me. I've added this in the settings.json file

```

    "phpfmt.indent_with_space": 2,
    "phpfmt.cakephp": true,
    "phpfmt.passes": ["AlignTypehint", "AlignEquals", "AlignDoubleArrow"],
    "phpfmt.psr2": false,
    "phpfmt.exclude": ["AllmanStyleBraces"]
```
Please tell the fix.
