### ISSUE TITLE
allow cakephp option

### ISSUE THREAD

**Issue by logorrhea** [kokororin/vscode-phpfmt#3]
Would it be possible to expose the `--cakephp` formatting option from `fmt.phar`? It is much closer to my company's coding standards than psr1 or 2. Or for that matter, is is possible to just use the document tab settings rather than a coding standard?

**Comment by kokororin** [comment]
Oh, I forgot it. Can you try the `1.0.9` release?

**Comment by logorrhea** [comment]
Yeah that works, thank you :) It does still seem to be formatting with spaces, though. I suppose because `--indent-with-spaces` is always being sent no matter how I configure the plugin. What do you think about removing that flag if the user specifies a value less than zero? For example `"phpfmt.indent_with_space": -1`.

**Comment by kokororin** [comment]
Maybe phpfmt.custom_arguments can solve this problem temporarily
