### ISSUE TITLE
Selection format clears indenation

### ISSUE THREAD

**Issue by mleopold** [kokororin/vscode-phpfmt#30]
Hi.
I often use the selection-formating, but I've found that some times this results in the indentation being cleared completely. Selecting lines 3-6 (the $a assignment) results in the formatting below:
```
class MyFantasticClass {
  public function test() {
    $a = array(
      'a' => 1,
      'b' => 2
    );
    echo 'Something or other';
  }
}
```
Result:
```
class MyFantasticClass {
  public function test() {
$a = array(
 'a' => 1,
 'b' => 2,
);
    echo 'Something or other';
  }
}
```

- Martin

**Comment by kokororin** [comment]
duplicate as https://github.com/kokororin/vscode-phpfmt/issues/7
