### ISSUE TITLE
windows u s e r n a m e : wrap extensionPath and pharRelPath in double quotes

### ISSUE THREAD

**Issue by marchage** [kokororin/vscode-phpfmt#31]
Hi,

Just something that fixed failures on my machine:

in /out/src/PHPFmt.js:128 you could wrap the result of `path.join()` in double quotes.

```javascript
args.unshift('"' + path.join(context.extensionPath, pkg.config.pharRelPath) + '"');
```
That way if "anybody" has spaces in their windows username your extension would still work.

Hope this helps,

Marc

**Comment by kokororin** [comment]
Thank you

**Comment by th-santos** [comment]
Should be implemented!
