### ISSUE TITLE
Editorconfig Integration

### ISSUE THREAD

**Issue by chez14** [kokororin/vscode-phpfmt#39]
Hey guys, do you support `editorconfig`?

I've tried set one, but it's not working.

**Comment by kokororin** [comment]
No.

**Comment by kokororin** [comment]
Can you see the commands in F1, does it work?

**Comment by chez14** [comment]
Yes, it shows up the `Format Document`, click it right away, then shows this cute error message:

```plain
There is no document formatter for 'php'-files installed.
```

**Comment by kokororin** [comment]
I haven't met this error. Maybe is conflicted with other extensions

**Comment by chez14** [comment]
Hmm i'm pretty much sure have disabled all those PHP extensions. Sorry, what OS are you using? I got Windows and Ubuntu, both of them have different plugin behavior, should i checked yours too.

Anyway, thanks for help, i'll find an npmjs package for it.
