### ISSUE TITLE
Group use declarations

### ISSUE THREAD

**Issue by ManuelMolina97** [kokororin/vscode-phpfmt#5]
When I have a group declaration of use, like the following one:

```php
use Namespace\{
    ClassX,
    ClassY,
    ClassZ,
};
```

And I format it, it turns into this:

```php
use Namespace\ClassX;
use Namespace\ClassY;
use Namespace\ClassZ;
```

So I think it should stay like the first one, as it is a [feature](http://php.net/manual/de/migration70.new-features.php#migration70.new-features.group-use-declarations) of PHP7.

**Comment by kokororin** [comment]
This VSCode Extension is base on **phpfmt**. But its development seem to be stopped in 2016.
Some one has continue developing. See [subins2000/phpF](https://github.com/subins2000/phpF)
But **phpF** also have not this feature.
You can open issue in the phpF repo.
