### ISSUE TITLE
should indent at second line in a single expression

### ISSUE THREAD

**Issue by seoker** [kokororin/vscode-phpfmt#50]
I have something like this:
```php
$foo = isset($a)
    and isset($b);
```
It converts to
```php
$foo = isset($a)
and isset($b);
```
I think it's better to have an indent at the second line, any config for this?

**Comment by ecrmnn** [comment]
This is a big one for me as it breaks our company style guide.

Did you find a solution for this?

**Comment by seoker** [comment]
So far not yet, still waiting for a solution.

**Comment by ecrmnn** [comment]
I never found a solution to this either, but I've switched to using [`php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) directly instead of this extension.
