### ISSUE TITLE
A few issues, might be they are questions, whether phpfmt is true OR i am false.

### ISSUE THREAD

**Issue by aaimaawebs** [kokororin/vscode-phpfmt#51]
1. It increases space before comment end asterisk , please check it in below screenshot.

![phpfmt-issues-1](https://user-images.githubusercontent.com/25567939/45695661-7e5c0280-bb7f-11e8-9e48-589de39c53c8.PNG)

2. Also, it converts Logical operators (and TRUE, FALSE, NULL) in small letters, for example phpfmt will convert 'OR' to 'or' & 'TRUE' to 'true' & 'NULL' to 'null'. Please refer above screenshot.

3.  And, it also adds ',' (comma) in last value to end. Please have a look on screenshot below:
![phpfmt-issues-2](https://user-images.githubusercontent.com/25567939/45695990-2ffb3380-bb80-11e8-876b-3dc4853a6ecc.PNG)
 
4. And, it also add method to 'public' if there nothing mentioned something method type. For example:
![phpfmt-issues-3](https://user-images.githubusercontent.com/25567939/45696148-8b2d2600-bb80-11e8-8515-0e1d0c41408e.PNG)

**Comment by kokororin** [comment]
Disable PSR2

**Comment by aaimaawebs** [comment]
Thanks @kokororin for supporting.

I disabled PSR2 and it's partially useful. As it now, it now switch 'FALSE' to 'false' and it still adding space before asterisk(*) in comments ending. Also, adding ',' (comma) in the end, as shown in screenshot.

Unfortunately, I committed previous code formatted without disabling PSR2 :'(

** Other issues can be resolved?
