### ISSUE TITLE
New Line before else

### ISSUE THREAD

**Issue by christhofer** [kokororin/vscode-phpfmt#59]
The plugin currently change

```
if (statement) {
    // do something
}
elseif (other statement) {
    // do other thing
}
```

into

```
if (statement) {
    // do something
} elseif (other statement) {
    // do other thing
}
```

How to turn this off?
I can't find it in the documentation.

**Comment by attisan** [comment]
@kokororin has this been fixed?

**Comment by scottalan** [comment]
I've been trying to turn this off as well; is it even possible? Same goes for `try/catch` as well?

**Comment by driade** [comment]
Hi, the culprit is the "MergeParenCloseWithCurlyOpen" pass. You can exclude it an check if it's fine for you.
