### ISSUE TITLE
PHP_VERSION_ID validation seams to be wrong

### ISSUE THREAD

**Issue by marcosgallardo** [kokororin/vscode-phpfmt#6]
https://github.com/kokororin/vscode-phpfmt/blob/d2c599e60d511ea4cc6db54f486b7f1f61a3d198/src/PHPFmt.ts#L108

I'm running a `PHP Version 5.6.30` and I get this error.
If I run `php -r 'echo PHP_VERSION_ID;'` the output is `50630`

I see you are validation against `56000` and I belive you should be validation against `50600`.

If you check the [PHP manual](http://php.net/manual/es/reserved.constants.php) if `PHP` version is `5.2.7` the value for `PHP_VERSION_ID` will be `50207`.

Chears!

**Comment by marcosgallardo** [comment]
Wrong place to open an issue, sorry

**Comment by kokororin** [comment]
Thank you! `1.0.12` has published.
