### ISSUE TITLE
php 7.3 warning

### ISSUE THREAD

**Issue by di3663** [kokororin/vscode-phpfmt#62]
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar://D:/TOOL/php/phpfmt.phar/fmt.stub.php on line 8087
```

**Comment by Sotiris-k** [comment]
I'm also using PHP 7.3 and this warning clutters up my error log every time I use phpfmt.

I'd create a PR request for the phpfmt repository fixing it but I don't think it's there anymore.

**Comment by di3663** [comment]
Yes. It seems the repo of phpfmt is gone.

@Sotiris-k
