### ISSUE TITLE
Array space missing

### ISSUE THREAD

**Issue by jjasoncool** [kokororin/vscode-phpfmt#7]
I have some pictures by formatting the files:
![before](https://user-images.githubusercontent.com/24731867/33410326-a4a1d8e4-d5ba-11e7-8ed0-f451cdfa1e5f.png)
![after](https://user-images.githubusercontent.com/24731867/33410334-aea80840-d5ba-11e7-9e38-0d3994ad28a8.png)

Because I need to keep the space to made array readable.
Can do this by change my local setting?

By the way, can I only format selected code area?

Thanks!

**Comment by kokororin** [comment]
> Can do this by change my local setting?
No. Please see https://github.com/kokororin/vscode-phpfmt#read-this-first

> By the way, can I only format selected code area?
In the future version, maybe.

**Comment by kokororin** [comment]
Please upgrade to `1.0.13`

**Comment by jjasoncool** [comment]
Thank you!!!

**Comment by jjasoncool** [comment]
Sorry , I found one problem.
when I format my code, my indent will missing.
but format all code will not.

Is this normal?


![video_2017-12-07_144345](https://user-images.githubusercontent.com/24731867/33706246-77cde376-db6e-11e7-9542-1d82cd70e7ec.gif)

**Comment by kokororin** [comment]
Sorry, I don't know how to implement this.

**Comment by jjasoncool** [comment]
excuse me, can the extension support point to the phar file like [http://cs.sensiolabs.org/](this) ?

**Comment by kokororin** [comment]
phpfmt and php-cs-fixer are different.
You can use https://github.com/Dickurt/vscode-php-formatter

**Comment by jjasoncool** [comment]
Thank you ,but I prefer to use phpfmt more than others tools :)
