### ISSUE TITLE
How do i configure phpfmt?

### ISSUE THREAD

**Issue by geniusunil** [kokororin/vscode-phpfmt#77]
Everybody is talking about changing settings like:
 "phpfmt.php_bin": "\"C:\\Program Files\\php\\php.exe\""

But where do i paste this?

**Comment by Galzor** [comment]
in settings.json of your VS code.
you can access it easilly, just press `F1 or Ctrl+Shift+P ` and type `settings`
but its recommended to set this in your system's path instead doing in settings.json. it will automatically pick up from there.

**Comment by kanlukasz** [comment]
> 
> 
> Everybody is talking about changing settings like:
> "phpfmt.php_bin": ""C:\Program Files\php\php.exe""
> 

@geniusunil - keep in mind that in Win you have to use double `\\`.

The correct setting is:
`"phpfmt.php_bin": "C:\\Program Files\\php\\php.exe",`

Ps. If you use PHP with XAMPP it will be:
`"phpfmt.php_bin": "C:\\xampp\\php\\php.exe",`
