### ISSUE TITLE
Is it possible to disable deleting namespaces if I don't use them Yet

### ISSUE THREAD

**Issue by dseegers** [kokororin/vscode-phpfmt#79]
Hey there, 

Thanks for making this amazing plug-in 👍 .
I wondered if it was possible not to delete the namespaces if they are not being used yet. I often create Controllers (by copying) from other controllers. These have namespaces that will be used later (but not immediately). Now it is a bit unfortunate that these will be deleted if I format my code, haha :)

**Comment by nomadbard916** [comment]
Add in setting.json,
"phpfmt.exclude": [
        "OrderAndRemoveUseClauses"
    ],
And it's done.
