### ISSUE TITLE
`indent_with_space` validation seams to be wrong

### ISSUE THREAD

**Issue by marcosgallardo** [kokororin/vscode-phpfmt#8]
https://github.com/kokororin/vscode-phpfmt/blob/7fa71157e7651d9c771bccbeb71bf7d6884f96e7/src/PHPFmt.ts#L47

It's not reading the default value for `indent_with_space` (`eg: 4 spaces`)

Not sure, but maybe to fix it, you should validate `spaces > 0` first and then if is `boolean`.

Chears!

**Comment by kokororin** [comment]
Default value of `indent_with_space` is 4. and `4 === true` is false.
I think it works.

But I found a bug which may produce some error:
When changed some config, the config would not be updated correctly.
Can you try the `1.0.14`?
If there is still bug, please enable `phpfmt.debug_mode` to the commands output.

**Comment by marcosgallardo** [comment]
I just found the actual error. I had setted `"phpfmt.detect_indent": true`.
My bad, I'm really sorry.

By the way, I set `"phpfmt.debug_mode": true` and I couldn't see any output on the `console`.

![ss](https://user-images.githubusercontent.com/4549886/33559848-d9cee43c-d8ec-11e7-95ad-a1a5ede6cfe6.gif)

**Comment by kokororin** [comment]
Wow. The output is in `Developer Tools`.
Can Open it in Help > Toggle Developer Tools!
