### ISSUE TITLE
Inline php in HTML gets wrongly indented

### ISSUE THREAD

**Issue by BasvanH** [kokororin/vscode-phpfmt#82]
If I add php code inline which is not sticked against the httml code, it will be wrongfully indented.

This gets indented far away from it's original position.
`<input type="checkbox" id="winrm_status" name="winrm_status" <?php echo ($thisChecked ? 'checked' : ''); ?> >`

If done like this so the php is attached to the html code, it sticks on it's place
`<input type="checkbox" id="winrm_status" name="winrm_status"<?php echo ($thisChecked ? ' checked' : ''); ?> >`

Is there an existing option to disable indent on inline html & php?

**Comment by Kennethjk3** [comment]
Maybe due to not having the closing `>` on the `<input>` tag is causing the it to bug out?

**Comment by BasvanH** [comment]
> Maybe due to not having the closing `>` on the `<input>` tag is causing the it to bug out?

Well spotted, but this is unfortunately a typo in the created issue. In code we do have the closing `>`. Have changed the original post. Thanks!

**Comment by Kennethjk3** [comment]
Looked into it real briefly 

maybe adding this line to settings.json
`"phpfmt.passes": ["AlignPHPCode",]`

This is the full settings I found on the interwebz, hopefull it helps
```
//phpfmt
"phpfmt.php_bin": "php",
"phpfmt.passes": [
    "AlignPHPCode",
    "AlignTypeHint",
    "AddMissingParentheses",
    "ConvertOpenTagWithEcho",
    "DocBlockToComment",
    "IndentTernaryConditions",
    "JoinToImplode",
    "PSR2KeywordsLowerCase",
    "PSR2LnAfterNamespace",
    "PSR2CurlyOpenNextLine",
    "PSR2ModifierVisibilityStaticOrder",
    "PSR2SingleEmptyLineAndStripClosingTag",
    "ReindentSwitchBlocks",
    "RemoveUseLeadingSlash",
    "StripExtraCommaInArray",
    "SpaceBetweenMethods",
],
"phpfmt.exclude": [
    "ReindentComments",
    "StripNewlineWithinClassBody"
],
"phpfmt.psr2": false,
```

I use beautify with these in my settings and i dont have to many issues with it
![](https://im2.ezgif.com/tmp/ezgif-2-c8af034eefdc.gif)
```
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "jsonc"
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautifyrc"
      ]
    },
    "css": [
      "css",
      "less",
      "scss"
    ],
    "html": [
      "htm",
      "html",
      "php"
    ]
  },
```

Good luck!

**Comment by BasvanH** [comment]
Thanks! I had already set the "AlignPHPCode". I finally got a solution. Apparently it's not PHPfmt whose doing the wrong indent, It's Code own formatting.

I have set these options, and now it works as expected.
```
"html.format.wrapAttributes": "auto",
"html.format.wrapLineLength": 0
```

**Comment by BasvanH** [comment]
Well, seems like in some cercomstances the code still gets wrngly indented. When I remove `AlignPHPCode `from the passes, the problem is gone. So `AlignPHPCode `needs to be adjusted so it excludes lines where <?php and ?> are on the same row.

**Comment by rexsolus2021** [comment]
try "Format HTML in PHP " after "phpfmt".

**Comment by vandijkstef** [comment]
Adding another case; take this input

`<ol class="product-items <?php echo /* @noEscape */$type?>">`

It will get formatted to

`<ol class="product-items<?php echo /* @noEscape */$type ?>">`

Note the space after `product-items` disappeared
