### ISSUE TITLE
Removes space between type and variable name

### ISSUE THREAD

**Issue by mougui2** [kokororin/vscode-phpfmt#88]
Hello,
when I use this formatter it removes spaces between my types and my variables : 
Before Alt+MAJ+F
![image](https://user-images.githubusercontent.com/57803410/160346294-2ab6a0cf-41e6-4d93-8431-ccbb3b36207b.png)
After Alt+MAJ+F
![image](https://user-images.githubusercontent.com/57803410/160346389-28d3c630-de73-4869-9658-1a4044b757c0.png)

here's my config : 
![image](https://user-images.githubusercontent.com/57803410/160346623-b92cd984-3391-4e68-945c-cd3d3ece1572.png)

Is there a special parameter to prevent this ?

**Comment by ArmandBahi** [comment]
Hi, did you found a solution for that ?
