### ISSUE TITLE
Formatting error when type hinting class properties in PHP 8

### ISSUE THREAD

**Issue by murugappanrm** [kokororin/vscode-phpfmt#91]
This is my code:

```
<?php

declare (strict_types = 1);

class Transaction
{
  public int $test = 10;
}
```
After saving the file, the formatter formats the$test property wrongly: 

```
<?php

declare (strict_types = 1);

class Transaction
{
 intpublic $test = 10;
}
```

**Comment by murugappanrm** [comment]
Hi,
Is there any resolution to the problem? This bug is making the usefulness of  VS Code Editor to become less.

**Comment by Jphn** [comment]
The current version of phpfmt does not support class property type hinting. You will need to use a different PHP formatter. I recommend trying PHP Tools extension by DEVSENSE, it provides basic code formation, IntelliSense and some more features.

**Comment by cobraprojects** [comment]
Just add `"phpfmt.psr2": false,` in your `settings.json` file

**Comment by murugappanrm** [comment]
@cobraprojects 
I have set the setting as in the attached screen cap. Is that ok?

![Screenshot_1](https://user-images.githubusercontent.com/63133893/180641783-c5e6324e-9556-4b80-991e-b2feddcc3907.png)

**Comment by murugappanrm** [comment]
Hi,
Thank you for the update. I did that already but the only trouble is Devsense seems to have lots of problems with Codeigniter 4. So sad. 

Regards from, Murugappan Ramanathan 

    On Monday, 13 June 2022 at 10:14:13 am MYT, João Pedro Holanda Neves ***@***.***> wrote:  
 
 


The current version of phpfmt does not support class property type hinting. You will need to use a different PHP formatter. I recommend trying PHP Tools extension by DEVSENSE, it provides basic code formation, IntelliSense and some more features.

**Comment by TysiacSzescset** [comment]
For me issue was resolved by adding this to settings.json:

    "phpfmt.exclude": [
        "PSR2ModifierVisibilityStaticOrder"
    ]

No need to disable whole PSR2 formatting.

**Comment by murugappanrm** [comment]
@TysiacSzescset  after making changes as you suggested, it seems to be working now. Thank you.
