### ISSUE TITLE
phpfmt: Format failed - syntax errors found

### ISSUE THREAD

**Issue by a4ajay36** [kokororin/vscode-phpfmt#93]
Command failed: php -l /var/folders/g4/08mc5dnx57qb_zr7l4f813900000gn/T/temp-zafedwzza.php
PHP Fatal error:  Constant expression contains invalid operations in /var/folders/g4/08mc5dnx57qb_zr7l4f813900000gn/T/temp-zafedwzza.php on line 46

**Comment by markeissler** [comment]
I see this type of error as well when trying to use this extension. End result: can't use the extension. I'm developing in a remote container with `PHP 8.1.11`.
