### ISSUE TITLE
can option "ignore" be added?

### ISSUE THREAD

**Issue by nmfmcosta** [kokororin/vscode-phpfmt#97]
Hello,

How can I exclude files / folders with patterns from being parsed?

phpfmt allows the following option:

--ignore=PATTERN-1,PATTERN-N,...  ignore file names whose names contain any PATTERN-N

I tried using custom_arguments:

"phpfmt.custom_arguments":" --ignore=<mypattern>",

But the output is: 

.vscode\extensions\kokororin.vscode-phpfmt-1.0.31\node_modules\phpfmt\fmt.phar" --ignore=<mypattern>

Can "ignore" be a new setting on the plugin?

Thanks in advance

**Comment by vandijkstef** [comment]
+1. Wouldn't mind having a comment in the file either `// @phpfmt-ignore`

**Comment by lucasferreira** [comment]
Hi @nmfmcosta 

I've made some PR to work on this https://github.com/kokororin/vscode-phpfmt/pull/101
