### ISSUE TITLE
Deprecation warning on install: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by natejank** [kokororin/vscode-phpfmt#98]
When installing the extension, I received the following warning:
`(node:72817) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by kokororin** [comment]
fixed in 1.1.4
