### ISSUE TITLE
conts not formatted at all

### ISSUE THREAD

**Issue by daidaiworm** [kokororin/vscode-phpfmt#99]
```
<?php

class NullNothig
{
    const age =125;
                const A =5;
const a =6;
    const AGGGD=4;
    const ABC=18;
    const AGENAME=666;

    public function age()
    {}
    function name_user(){}
}
```

it should be formatted like this.
```

<?php

class NullNothig
{
    const AGE     = 125;
    const A       = 5;
    const A       = 6;
    const AGGGD   = 4;
    const ABC     = 18;
    const AGENAME = 666;

    public function age()
    {}
    public function nameUser()
    {}
}
```

**Comment by amoschristian** [comment]
![image](https://user-images.githubusercontent.com/46567795/223657553-812ec747-618f-4c24-91ee-9ca0ab5ef399.png)

It does working on my end, using your unformatted sample and then format using phpfmt

**Comment by lucasferreira** [comment]
Hi @daidaiworm 

This is because this extension are now using and old version of PHPFMT project, I've made some PR to update PHPFMT package AND get oficial support to PHP8 https://github.com/kokororin/vscode-phpfmt/pull/101
